"use strict";

/**
 * Gameplay calculation facade for legacy callers.
 *
 * New formulas are delegated to js/rules/*; these wrappers adapt current DATA/state
 * into the pure rule inputs expected by the refactored architecture.
 */
/** Return the effective level used by content gates while player level remains unlimited. */
function contentRequirementLevel(level){
  return window.DragonRules.progression.contentRequirementLevel(level);
}
/** Dragon slots available in a Habitat level. */
function habitatCapacity(level){
  return window.DragonRules.buildings.capacityAt(level,window.DragonConfig.buildings.habitat.dragonCapacity);
}
/** Egg slots available in a Hatchery level. */
function hatcheryCapacity(level){
  return window.DragonRules.buildings.capacityAt(level,window.DragonConfig.buildings.hatchery.nests);
}
function habitatHasRoom(building){return building.type==="habitat"&&!building.stored&&!building.upgradeEnds&&
  occupants(building).length<habitatCapacity(building.level);}
/** XP required for the next player level. */
function playerXPNeeded(level){
  return window.DragonRules.progression.playerXPNeeded(level);
}
function dragonXPNeeded(level){
  const xp=window.DragonConfig.dragons.xp;
  return Math.ceil(xp.base*Math.pow(level,xp.exponent));
}
/** Food consumed by one feed action at a dragon level. */
function dragonFeedCost(level){
  return window.DragonRules.progression.dragonFeedCost(level,window.DragonConfig.progression.dragonMaxLevel);
}
/** Maximum Farm count unlocked for a player level. */
function farmLimit(level){
  return window.DragonRules.progression.farmLimit(level);
}
function farmCount(){return state.buildings.filter(function(b){return b.type==="farm";}).length;}
/** Current dragon level cap derived from the active Dragon Academy. */
function dragonLevelCap(){
  const academy=state?.buildings.find(b=>b.type==="academy"&&!b.stored);
  const caps=window.DragonConfig.progression.academyCaps;
  return academy?caps[Math.min(academy.level-1,caps.length-1)]:
    window.DragonConfig.dragons.initialLevelCapWithoutAcademy;
}
/** Cost and ownership gates for the next Dragon Academy level. */
function academyUpgradeCost(level){
  return window.DragonRules.buildings.academyUpgradeCost(
    level,window.DragonConfig.progression.academyUpgrades[level-1],dragonLevelCap(),contentRequirementLevel);
}
/** Count owned dragons meeting an Academy upgrade's required dragon level. */
function academyQualifiedDragonCount(cost){
  if(!cost)return 0;
  return state.dragons.filter(function(dragon){
    return dragon.level>=cost.requiredDragonLevel;
  }).length;
}
/** Normalized number of feeds already applied toward the next dragon level. */
function dragonFeedProgress(dragon){
  return clamp(Math.floor(Number(dragon.feedProgress)||0),0,window.DragonConfig.world.feeding.feedsPerLevel-1);
}
/** Human-readable dragon lifecycle stage used by UI/art. */
function stageOf(dragon){
  const stages=window.DragonConfig.dragons.stages;
  return dragon.level<stages.adultAt?"Young":dragon.level<stages.elderAt?"Adult":"Elder";
}
/** Return current combat stats for one owned dragon. */
function dragonStats(dragon){
  const species=DATA.species[dragon.species];
  return window.DragonCombat.stats(species.elements,species.rarity,dragon.level,
    DRAGON_DB.elements,DRAGON_DB.rarities,dragon.stars);
}
/** Return the shared Combat Power score derived from the dragon's current combat stats. */
function dragonCombatPower(dragon){
  return window.DragonCombat.power(dragonStats(dragon));
}
/**
 * Gold/hour generated by one dragon in a Habitat.
 * Level growth comes from progression config; care/Habitat multipliers come from world rules.
 */
function dragonIncome(dragon,building){
  const base=DATA.rarities[DATA.species[dragon.species].rarity].income;
  const steps=Math.max(0,Math.min(window.DragonConfig.progression.dragonMaxLevel,dragon.level)-1);
  const rates=window.DragonConfig.progression.incomeGrowth;
  const growth=1+rates.linear*steps+rates.quadratic*steps*steps;
  return base*growth*rates.multiplier*window.DragonRules.world.incomeMultiplier(dragon,building.level);
}
/** Convert one dragon's configured hourly Gold income to per-minute production. */
function dragonIncomePerMinute(dragon,building){
  return dragonIncome(dragon,building)/60;
}
/** Sum per-minute Gold production for all dragons housed in an active Habitat. */
function habitatIncomePerMinute(building){
  if(!building||building.type!=="habitat"||building.stored)return 0;
  return occupants(building).reduce(function(sum,d){return sum+dragonIncomePerMinute(d,building);},0);
}
/** Maximum uncollected Gold stored by a Habitat. */
function habitatGoldCapacity(building){
  return window.DragonRules.buildings.habitatGoldCapacity(building.level,ELEMENT_UNLOCK[building.element]||1);
}
/** Maximum uncollected Gems stored by a Habitat. */
function habitatGemCapacity(building){
  return window.DragonRules.buildings.habitatGemCapacity(building.level,ELEMENT_UNLOCK[building.element]||1);
}
/** Purchase price for the next Habitat of an element. */
function habitatPurchaseCost(element,purchased=state?.habitatPurchases?.[element]||0){
  return window.DragonRules.buildings.habitatPurchaseCost(
    window.DragonConfig.buildings.definitions.habitat.cost,ELEMENT_UNLOCK[element]||1,purchased);
}
/** Return the current purchase cost for a building type; Habitats include element/repeat scaling. */
function buildingPurchaseCost(type,element){
  return type==='habitat'?habitatPurchaseCost(element):window.DragonConfig.buildings.definitions[type].cost;
}
/** Incubation/breeding tier derived from species structure. */
function dragonTimeTier(species){return window.DragonRules.hatching.tierOf(species);}
/** Egg incubation duration in seconds. */
function hatchingSeconds(species){
  return window.DragonRules.hatching.seconds(species,ELEMENT_UNLOCK);
}
/** Shop price for a pure-element egg. */
function shopEggPrice(species){
  return window.DragonRules.buildings.eggPrice(
    species.detail.giaTrung,species.rarity,ELEMENT_UNLOCK[species.elements[0]]||1);
}
/** Return passive Gem/hour production for dragons housed in an active Habitat. */
function habitatGemRate(building){return !building||building.type!=="habitat"||building.stored?0:
  occupants(building).length*window.DragonConfig.world.gemPerDragonPerHour;}
/** Estimate seconds until the next housed dragon completes one Gem production cycle. */
function gemNextSeconds(building){
  if(!building||building.type!=="habitat"||building.stored)return 0;
  if((building.storedGems||0)>=habitatGemCapacity(building))return 0;
  const dragons=occupants(building);
  if(!dragons.length)return 0;
  return Math.ceil((1-Math.max(...dragons.map(function(d){return d.gemProgress||0;})))*
    window.DragonConfig.world.gemSecondsPerHour/window.DragonConfig.world.gemPerDragonPerHour);
}
/** Gold component of a standard building upgrade. */
function upgradeCost(building){
  const base=building.type==="habitat"?habitatPurchaseCost(building.element,0):
    buildingPurchaseCost(building.type,building.element);
  return window.DragonRules.buildings.upgradeGoldCost(base,building.level);
}
/** Gold+Gem cost of Habitat/Farm/Hatchery upgrades. */
function standardUpgradeCost(building){
  const base=building.type==="habitat"?habitatPurchaseCost(building.element,0):
    buildingPurchaseCost(building.type,building.element);
  const unlock=contentRequirementLevel(ELEMENT_UNLOCK[building.element]||1);
  return window.DragonRules.buildings.standardUpgradeCost(building.type,building.level,base,unlock);
}
/** Upgrade duration in seconds; Habitat time also scales by element unlock tier. */
function upgradeSeconds(building){
  const times=window.DragonConfig.buildings.upgradeTimes[building.type];
  if(!times)return 0;
  const base=times[Math.min(building.level-1,times.length-1)];
  if(building.type!=="habitat")return base;
  return window.DragonRules.buildings.habitatUpgradeSeconds(
    base,contentRequirementLevel(ELEMENT_UNLOCK[building.element]||1));
}
/** Player-level gate for upgrading from the current Hatchery level. */
function hatcheryUpgradePlayerLevel(level){
  const gates=window.DragonConfig.progression.hatcheryUpgradeLevels;
  return contentRequirementLevel(gates[Math.max(0,Math.floor(Number(level)||1)-1)]||1);
}
/** Gem price for unlocking an island index. */
function islandUnlockCost(index){return window.DragonRules.buildings.islandUnlockCost(index);}
function islandUnlockIssue(index){
  const island=DATA.islands[index];
  if(!island||index<=0||index!==state.unlockedIslands)return "Unlock the previous island first.";
  if(!islandComplete(index-1))return "Fully unlock "+DATA.islands[index-1].name+" before buying the next island.";
  const level=contentRequirementLevel(Math.max(island.playerLevel||1,DATA.elementUnlocks[island.element]||1));
  if(state.player.level<level)return "Requires player level "+level+" to unlock "+island.name+" and buy its element egg.";
  if(island.element&&!state.dragons.some(function(dragon){
    return DATA.species[dragon.species]?.elements.includes(island.element);
  }))return "Own at least one dragon with the "+DATA.elements[island.element].name+" element to unlock "+island.name+".";
  const cost=islandUnlockCost(index);
  if(state.gems<cost)return "Requires "+cost+" gems to unlock "+island.name+".";
  return "";
}
/** Gold price for a land region on an island tier. */
function landRegionCost(index,opened){
  return window.DragonRules.buildings.landRegionCost(index,opened);
}
function landCost(x,y){
  const region=regionOf(x,y),index=region?.index||0;
  return landRegionCost(index,region?islandRegionCount(index):1)/DATA.islandRegionSize**2;
}
/** Return locked tile keys that would be opened by the land region containing x/y. */
function expansionTiles(x,y){
  const r=regionOf(x,y),tiles=[];
  if(!r||r.index>=state.unlockedIslands)return tiles;
  for(let dy=0;dy<DATA.islandRegionSize;dy++)for(let dx=0;dx<DATA.islandRegionSize;dx++){
    const px=r.x+dx,py=r.y+dy;
    if(!unlocked(px,py))tiles.push(key(px,py));
  }
  return tiles;
}
/** Return Gold cost for the still-locked tiles in the selected expansion region. */
function expansionCost(x,y){return Math.round(landCost(x,y)*expansionTiles(x,y).length);}
/** Instant Gem alternative for a land expansion. */
function expansionGemCost(x,y){
  return window.DragonRules.buildings.goldToGemCost(expansionCost(x,y));
}
function cropById(id){return DATA.crops.find(function(c){return c.id===id;});}
